paths:
  data_dir: data
  data_raw: data/raw/milling_machine.csv
  data_processed: data/processed/milling_machine.parquet
  artifacts_dir: artifacts
  final_dir: artifacts/final
  split_dir: artifacts/split
  static_dir: api/static


features:
  target: Machine Failure
  numerical:
    - Air temperature [K]
    - Process temperature [K]
    - Rotational speed [rpm]
    - Torque [Nm]
    - Tool wear [min]
  categorical:
    - Type